/* 
if ..else
switch...case
for
while
do...while
infinite loops
for...in
for...of
break and contine
**/

/*

1. if...else
	if(condition){
		statment
	}else if(anotheroCondition){
		statment
	}...
	else{
		statments
	}
	Taks : If hour is between 6AM and 12 PM : Good Morneing, If it is between 12pm and 6pm - Good afternon, other wise Good Evening.
**/

let hour = 12;

if(hour > 6 && hour<12){
	console.log("Good Morning");
}else if (hour >=12 && hour <18){
	console.log("Good Afternon");
}else{
	console.log("Good Evening");
}

/**
switch 
*/

let role = 'guest';

switch(role){
	case 'guest' :
		console.log('Guest User');
		break;
	case 'moderator' :
		console.log('Moderator User');
		break;
	default:
		console.log('Unknow User');
		break;
}

if(role == 'guest') console.log('Guest User');
else if(role == 'moderator') console.log('moderator User');
else console.log('Unknow User');

/**
	FOR
*/

for(let i=0; i<5; i++){
	console.log('Hello', i);
}

/**
while

*/
let i=0;
while(i<5){
	console.log('Hello', i);
	i++;
}

/**
do-while
*/

let j=0;
do{
	console.log('HelloWorld')
	j++;
}while(j<=5);

/**
infinite loop
*/

/**
For..in
*/
const person={
	name : 'Kishore',
	age: '28'
}

for(let key in person){
	console.log(key, person[key]);
}

const colors =['red', 'blue', 'green'];

for(let index in colors){
	console.log(index, colors[index]);
}
/**
for..of
*/
for(let index of colors){
	console.log(index, colors[index]);
}
/**
differnece Between for..in and for..of

'for in' loops over enumerable property names of an object.

'for of' (new in ES6) does use an object-specific iterator and loops over the values generated by that.
*/

/**
Break and continue
*/

let i3 =0;
while(i3<10){
	if(i3%2 == 0){
		i3++;
		continue;
	}
	console.log(i3);
	i3++;
}

/**
Exercise 1: 
Write a function that takes two numbers and returns maxium of the two.
*/

let maxNumber = max(5,7);
console.log(maxNumber);
function max(a, b){
	/*if(a<b){
		return b;
	}else{
		return a;
	}*/
	return (a<b) ? b: a;
}

/**
Exercise 1: 
Landscap
*/
function isLandscap(width, height){	
	if (width > height){
		return true;
	}else{
		return false;
	}
}


/**
Exercise 3: 
Fizz Buzz

If a number is divisble by 3 => Fizz
If a number is divisble by 5 => Buzz
If a number is divisble by both 3 and 5 => FizzBuzz
Not divisible by 3 or 5 is =
Not a number 
*/
const output = fizzBuzz(NaN);
console.log(output);

function fizzBuzz(input){
	if(typeof input !== 'number'){
		return 'Not a number';
	}
	if((input % 3 ==0) && (input % 5 ==0)){
		return 'FizzBuzz';
	}
	if(input % 3 ==0){
		return 'Fizz';
	}
	if(input % 5 ==0){
		return 'Buzz';
	}
	return input;
}

/**
Exercise 4: 
Demerit Points
 Speed Limit = 70
 5k -> 1 point
 
 12 points -> suspended
*/

const point = checkSpeed(90);
console.log(point);
function checkSpeed(speed){
	const speedLimit = 70;
	const kmPerPoint = 5;
	
	if(speed < speedLimit + kmPerPoint){
		return 'Ok';
	}
	const points = Math.floor((speed - speedLimit)/kmPerPoint);
	if(points >= 12){
		return 'License suspended';
	}else{
		return 'points : '+ points;
	}
}

/**
Exercise 5: 
Even and Odd
*/

showNumbers(10);
function showNumbers(limit ){
	for(let i=0; i<= limit; i++){
		const message = i%2 ===0 ? 'even': 'odd';
		console.log(i, message);
	}
}

/**
Exercise 6: 
Count Truthy
*/

const isActive = true;
const name = '';

if(name) console.log('Hello');

const array = [0, null, undefined, 1, 2, 3];

console.log(countTrunty(array));
function countTrunty(array){
	let count = 0;	
	for(let value of array){
		if(value )
			count++;
	}
	return count;
}

/**
Exercise 7: 
Show String properties
*/
const movie ={
	title : 'a',
	releaseYear : 2018,
	rating: 4.5,
	director: 'b'
};

showProperties(movie);

function showProperties(obj){
	for(let key in obj){
		if(typeof obj[key]=== 'string'){
			console.log(key, obj[key]);
		}
	}
	
}

/**
Exercise 8: 
Sum of multiple 3 and 5
*/
console.log(sum(10));

function sum(limit){
	let sum = 0;
	for(let i=0; i <= limit; i++){
		if( i%3 ===0 || i%5 === 0){
			sum += i;
		}
	}

	return sum;
}

/**
Exercise 9: 
Grade of Skill

Average = 70
 1- 59 : F
 60-69 : D
 70-79 : C
 80 - 89: B
 90 - 100 : A
*/

const marks = [80, 80, 50];
console.log(calculateGrade(marks));
function calculateGrade(marks){
	const average = calculateAverage(marks);
	
	if(average < 60 ){		return 'F';	}
	if(average < 70 ){		return 'D';	}
	if(average < 80 ){ 		return 'C';	}
	if(average < 90 ){		return 'B';	}
	return 'A';
}
function calculateAverage(array){
	let addtion = 0;
	for(let value1 of array){
		addtion += value1;
	}
	return addtion/array.length;
}

/**
Exercise 10: 
Stars
*/

showStars(5);

function showStars(rows){
	for(let row =1; row <= rows; row++){
		let pattern = '';
		for(let i=0; i< row; i++){
			pattern += '*';
		}
		console.log(pattern);
	}
}

/**
Exercise 10: 
Show prime numbers
12 = 1, 2, 3, 4, 6, 12.
*/

showPrimes(10);

function showPrimes(limit){
	for(let number=2; number<= limit; number++){
		if(isPrime(number)) console.log(number);
	}
}

function isPrime(number){
	for(let factor= 2; factor < number; factor++){
		if(number % factor === 0){
			return false;
		}
	}
	return true;
}